### ISSUE TITLE
CE (FireRescue1)

### ISSUE THREAD

**Issue by Firefly1965** [roysix/url-incrementer#22] opened 2024-11-04 23:04 UTC
### Description

Hello, I am a firefighter I was using your program to go through my continuing education. It was great for waiting and clicking the next button. However, with the last update, it has made it a little complicated. We use FireRescue1. I would send a url, but it requires a log in. I understand you are busy so any help is very much appreciated.

### URL

https://www.firerescue1academy.com/

### Version

Newest one

### Browser

Chrome

### OS

Windows 11

### Device

PC

**Comment by sixcious** [comment] 2024-11-05 00:14
Hi Firefly1965, thank you so much for using URLI and for opening this issue ❤️ 

Could you help me better understand how you're using URLI and what you're expecting it to do that is making it more complicated now? You mentioned it was great for "waiting and clicking the next button"; by "waiting," it sounds like you are using "AUTO" - is this correct?

To help me better understand how you're using the app, after you configure the settings in the UI Window and click the ACCCEPT Button, can you go back to the Setup view and click the Help (?) Button and click the "Copy Debug Button" and copy/paste your settings? You can remove the specific URLs from the data if you prefer not to share them publicly.

**Comment by Firefly1965** [comment] 2024-11-07 20:50
Well... I would share a url but you would need my log in. But basically...
we have continuing education. A video pops up and when the video is
finished, the next button pops up.

Before the update: the attachment was great. The video would play, the next
button appears, the attachment hits the next button automatically.

But with the attachment, the next button is missing and the incrementer
stops working because it cannot find the next button. I tried using the new
feature to fix it, but I was not able to figure it out.

Any assistance would be greatly appreciated. The guys love your program!

**Comment by sixcious** [comment] 2024-11-08 17:49
Hi again Firefly, thanks so much for the compliment! ❤️ Without having access to the website and at least seeing the settings you're using, I'm not sure if I can help much. Because this is a specific website issue, I need to know how you're using the app (the specific settings, e.g. which Action you're using, are you using AUTO, and so on) and I would also need access to the website so I can take a look and reproduce the issue.

> But with the attachment, the next button is missing and the incrementer
stops working because it cannot find the next button. I tried using the new
feature to fix it, but I was not able to figure it out.

The way this reads to me is that the next button is not appearing on the website, which URLI (the "attachment"?) can't control -- it obviously can't force a website to show a next button, which I'm sure you know. So, do you mean the next button *is* showing on the website, but URLI is not able to find it? If so, that sounds like you need to use the Next Link or Click Element action (from the list of actions on the left) and you need to provide the right path to the button on the page. There is an Element Picker button (to the right of the path input) that you can use to generate the path for you if you're unable to figure it out. Does that help?

**Comment by sixcious** [comment] 2024-12-27 21:35
Hi Firefly, I'm going to go ahead and close this, but please feel free to reply if you'd like to. Also, I released a new version recently with some improvements/fixes that might help.

Thank you ❤️

**Closed as completed by sixcious** 2024-12-27 21:35 UTC
Labels: question
